"""empty message

Revision ID: 16897dd3b599
Revises: 43001c492ce3
Create Date: 2017-11-10 20:58:53.972981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16897dd3b599'
down_revision = '43001c492ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('short_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'short_name')
    # ### end Alembic commands ###
