"""empty message

Revision ID: 35fe27f16cfc
Revises: 6384e8b84792
Create Date: 2018-01-07 17:23:29.264936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fe27f16cfc'
down_revision = '6384e8b84792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('valid_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'valid_time')
    # ### end Alembic commands ###
