"""empty message

Revision ID: 38ec35f26b2d
Revises: 16897dd3b599
Create Date: 2017-11-10 21:04:05.640695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ec35f26b2d'
down_revision = '16897dd3b599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column('groups', sa.Column('manager_name', sa.String(length=20), nullable=True))
    op.add_column('groups', sa.Column('tel_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'tel_public')
    op.drop_column('groups', 'manager_name')
    op.drop_column('groups', 'email')
    op.drop_column('groups', 'description')
    # ### end Alembic commands ###
