"""empty message

Revision ID: 62907e76d6c8
Revises: 4d2103e0fb36
Create Date: 2017-10-18 20:30:29.878560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62907e76d6c8'
down_revision = '4d2103e0fb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_card', sa.String(length=18), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('qq', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('school', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('student_no', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'student_no')
    op.drop_column('users', 'school')
    op.drop_column('users', 'qq')
    op.drop_column('users', 'name')
    op.drop_column('users', 'id_card')
    # ### end Alembic commands ###
