"""empty message

Revision ID: 43001c492ce3
Revises: 68d4146317ff
Create Date: 2017-11-10 16:27:23.513017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43001c492ce3'
down_revision = '68d4146317ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smstpls', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smstpls', 'title')
    # ### end Alembic commands ###
