"""empty message

Revision ID: 4d2103e0fb36
Revises: f06aeb9b3f52
Create Date: 2017-09-10 22:35:04.260027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2103e0fb36'
down_revision = 'f06aeb9b3f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('iid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'iid')
    # ### end Alembic commands ###
