"""empty message

Revision ID: e4c1cf1b2af5
Revises: 6f481145fcd6
Create Date: 2018-01-07 21:44:58.256039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c1cf1b2af5'
down_revision = '6f481145fcd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'uploads', 'users', ['owner_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'owner_id')
    # ### end Alembic commands ###
