"""empty message

Revision ID: f06aeb9b3f52
Revises: 046b41737afd
Create Date: 2017-09-10 00:52:25.555169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06aeb9b3f52'
down_revision = '046b41737afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('auth_token_expire', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_token_expire')
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###
